Observability
cessda/cessda.guidelines.public pull request #139
Opened 2024-01-19 15:41 UTC by Joshocan

2024-01-25 11:56 UTC, john-shepherdson commented on technical-infrastructure/observability/availability.md
> +A ping rrquest from Uptime Robot is sent to each endpoints every 5 minutes.
Typo on ´request´

2024-01-25 11:57 UTC, john-shepherdson commented on technical-infrastructure/observability/index.md
> +  CESSDA has [central logging system]({% link technical-infrastructure/observability/logging-overview.md %}) that collects, aggregates,
Typo ´CESSDA has a´

2024-01-25 11:59 UTC, john-shepherdson commented on technical-infrastructure/observability/index.md
> +  which then aid debugging process and problem solving capabilities.
typo ´aid the´

2024-01-25 12:01 UTC, john-shepherdson commented on technical-infrastructure/observability/monitoring-overview.md
> +instrumentation, tailoring the intrgration to suit the requirements of
Typo on ´integration´

2024-01-25 12:03 UTC, john-shepherdson commented on technical-infrastructure/observability/monitoring-overview.md
> +exposed with clients libraries and stored in a time series database. PromQL is
clients -> client
stored -> store them

2024-01-25 12:04 UTC, john-shepherdson commented on technical-infrastructure/observability/monitoring-overview.md
> +notifications and visualize and analyze metrics respectively.
visualize -> visualise
analyze -> analyse

2024-01-25 12:05 UTC, john-shepherdson commented on technical-infrastructure/observability/monitoring-overview.md
> + Metrics data stored in a time series database are retained on persistent
data is stored

2024-01-25 12:05 UTC, john-shepherdson reviewed
Please fix typos

2024-05-24 14:09 UTC, alencessda requested changes
Please check the comments on files. There are still a few typos and an update based on recent UptimeRobot subscription.

2024-05-24 14:09 UTC, alencessda commented on technical-infrastructure/observability/availability.md
> +[Helpdek system](https://helpdesk.cessda.eu/#dashboard)
Typo: Helpdesk

2024-08-23 10:40 UTC, matthew-morris-cessda commented
This is unlikely to be merged now

2024-08-23 10:40 UTC, closed without merging